name: CI

on:
  push:
    branches: 
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses : actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
    
      - name: install dependencies
        run : pip install -r python/requirements.txt

      - name: check python syntax
        run : python -m py_compile python/*.py

      - name: Start PostgreSQL
        run: docker compose up -d postgres

      - name: Wait for PostgreSQL
        run: |
          until docker compose exec -T postgres pg_isready -U postgres -d dnd; do
            sleep 2
          done

      - name: Check database
        run: |
          docker compose exec -T postgres \
            psql -U postgres -d dnd -c "\dt"

      - name: Stop PostgreSQL
        if: always()
        run: docker compose down
